### ISSUE TITLE
gene_to_omim error

### ISSUE THREAD

**Issue by slancast** [davetang/romim#1]
Running the exemplar gene_to_omim function, 

> gene_to_omim(gene_symbol = "FGFR2", show_query = FALSE)

 I get the following error:

Error in paste(my_search, my_include, my_key, sep = "&") : 
  object 'my_key' not found

Any help you could provide would be much appreciated.

**Comment by davetang** [comment]
Did you already use the set_key() function with a valid OMIM API key?

**Comment by slancast** [comment]
That solved that error, thanks. I'm getting a new one: 

> gene_to_omim(gene_symbol = "LUC7L", show_query = FALSE)

Error in open.connection(x, "rb") : HTTP error 429.

I appreciate your help. I tried googling these, but I seem to be the only/first one encountering them.

**Comment by davetang** [comment]
I have never encountered that error but the HTTP error code 429 means that you are making too many requests. Please try again later and refrain from making too many requests.

Their [API help page](https://www.omim.org/help/api) doesn't seem to say how many requests are allowed but perhaps I missed it.

**Comment by slancast** [comment]
Thanks for your help

**Comment by davetang** [comment]
You're welcome.
